version: 2.1

jobs:
  sonar-analysis:
    docker:
      - image: cimg/base:current # Base image or another as needed

    steps:
      - checkout
      - run:
          name: Install Java 17
          command: |
            sudo apt update
            sudo apt install -y openjdk-17-jdk
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH
            java -version # Verify Java 17 is set correctly
      - run:
          name: Install SonarScanner
          command: |
            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli.zip -d $HOME
            echo 'export PATH=$PATH:$HOME/sonar-scanner-4.6.2.2472-linux/bin' >> $BASH_ENV
            echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> $BASH_ENV
      - run:
          name: Run SonarQube Analysis
          command: |
            source $BASH_ENV
            sonar-scanner \
              -Dsonar.projectKey="Shavir-M_APDS_Customer_Payment_Portal" \
              -Dsonar.host.url="${SONAR_HOST_URL}" \
              -Dsonar.login="${SONAR_TOKEN}"

workflows:
  version: 2
  sonar-analysis-workflow:
    jobs:
      - sonar-analysis
