version: 2.1

jobs:
  sonar-analysis:
    docker:
      - image: cimg/base:current # or another image as needed

    steps:
      - checkout
      - run:
          name: Install Java 17
          command: |
            sudo apt update
            sudo apt install -y openjdk-17-jdk
            java -version # Verify that Java 17 is installed
      - run:
          name: Install SonarScanner
          command: |
            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip sonar-scanner-cli.zip -d $HOME
            echo 'export PATH=$PATH:$HOME/sonar-scanner-4.6.2.2472-linux/bin' >> $BASH_ENV
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey="Shavir-M_APDS_Customer_Payment_Portal" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.login="9126743be08a165b08b7b97119c69b095b94067e"

workflows:
  version: 2
  sonar-analysis-workflow:
    jobs:
      - sonar-analysis
