name: "ZAP Scan on Main Branch Update"

on:
  push:
    branches: [ "main" ]    # Runs when code is pushed to main branch
  pull_request:
    branches: [ "main" ]    # Runs on pull requests targeting main branch

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        docker pull owasp/zap2docker-stable:v2.11.1
        docker run --user root -v ${{ github.workspace }}:/zap/wrk/:rw --network=host -t owasp/zap2docker-stable:v2.11.1 zap-baseline.py -t https://www.zaproxy.org/ -J report_json.json -w report_md.md -r report_html.html

    - name: Upload ZAP Report as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: zap-report
        path: |
          report_json.json
          report_md.md
          report_html.html
