name: "ZAP Scan on Main Branch Update"

on:
  push:
    branches: [ "main" ]    # Run the scan when code is pushed to the main branch
  pull_request:
    branches: [ "main" ]    # Run the scan when a pull request is opened or updated targeting the main branch

jobs:
  zap_scan:
    runs-on: ubuntu-latest   # Use the ubuntu-latest runner
    name: Perform ZAP Full Scan

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4    # Checkout the repository to ensure the runner has access to the code

    - name: ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.11.0    # Run the ZAP full scan action
      with:
        target: 'https://www.zaproxy.org/'      # The target website to scan
